# Creating Numpy Arrays

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

# 2D & 3D ARRAY

In [4]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
#dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [7]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [8]:
#np.arange
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
#with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
#np.ones and np.zeroes
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#np.random
np.random.random((3,4))

array([[0.88217715, 0.58194698, 0.73926038, 0.24316522],
       [0.20526144, 0.07038484, 0.62470738, 0.07578646],
       [0.368744  , 0.03158695, 0.19332844, 0.96915771]])

In [15]:
#np.linspace
np.linspace(-10,10,10) #lower, upper, number of items

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [16]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

# Array Attribues

In [18]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [19]:
#ndim
a1.ndim

1

In [20]:
a2.ndim

2

In [21]:
a3.ndim

3

In [22]:
#shape
a1.shape

(10,)

In [23]:
a2.shape

(3, 4)

In [24]:
a3.shape

(2, 2, 2)

In [25]:
#size
a3.size
a2.size
a1.size

10

In [26]:
#itemsize
a1.itemsize

4

In [27]:
#dtype
a1.dtype

dtype('int32')

In [28]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

# Scaler operation

In [30]:
#arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [31]:
a2-5

array([[ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [32]:
#relational operators
a2>25

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [33]:
a1<10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [34]:
#vector operation
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# Array Function

In [36]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[40., 96.,  4.],
       [97., 63., 42.],
       [30.,  1., 44.]])

In [37]:
#max/min/sum/prod
np.max(a1)

97.0

In [38]:
np.sum(a1)

417.0

In [39]:
np.prod(a1)

5203873382400.0

In [40]:
#0- columns and 1-row
np.max(a1,axis=0)

array([97., 96., 44.])

In [41]:
np.max(a1,axis=1)

array([96., 97., 44.])

In [42]:
#mean/median/std/
np.mean(a1)
np.var(a1)

1054.4444444444446

In [43]:
#trignometric function
np.sin(a1)

array([[ 0.74511316,  0.98358775, -0.7568025 ],
       [ 0.37960774,  0.1673557 , -0.91652155],
       [-0.98803162,  0.84147098,  0.01770193]])

In [44]:
#dot products
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

In [45]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [47]:
#log and exponents
np.log(a1)

array([[3.68887945, 4.56434819, 1.38629436],
       [4.57471098, 4.14313473, 3.73766962],
       [3.40119738, 0.        , 3.78418963]])

In [48]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [49]:
#round/floor/ceil
np.random.random((2,3))*100

array([[72.79887553, 39.90256649, 60.93080439],
       [18.51572811, 33.44549629, 34.80286891]])

In [50]:
np.round(np.random.random((2,3))*100)

array([[99., 99., 98.],
       [78., 87., 11.]])

In [51]:
np.floor(np.random.random((2,3))*100)

array([[29., 43., 55.],
       [15., 59., 58.]])

In [52]:
np.ceil(np.random.random((2,3))*100)

array([[27., 70., 59.],
       [33., 99., 77.]])

# Indexing and Slicing

In [54]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [58]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
#locate 6 from a2
a2[1,2]

6

In [61]:
#locate 11 from a2
a2[2,3]

11

In [62]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
#locate 4 from a3
a3[1,0,0]

4

In [65]:
#locate 2 from a3
a3[0,1,0]

2

In [66]:
#locate 6 from a3
a3[1,1,0]

6

In [67]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
#print 2,3,4 from a1
a1[2:5]

array([2, 3, 4])

In [69]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
#print row 1 from a2
a2[0]

array([0, 1, 2, 3])

In [76]:
#print 2 ,6 and 10 from a2
a2[:,2]

array([ 2,  6, 10])

In [78]:
#print 5 ,6, and 10 from a2
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [79]:
#print all corner value from a2 that is 0,3,8,11
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [80]:
#print  value from a2 that is 1,3,9,11
#step 1 -
a2[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [81]:
#step2-
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [82]:
#print  value from a2 that is 4 ,7
a2[1,::3]

array([4, 7])

In [85]:
#1,2,3,5,6,7
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [89]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [93]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [99]:
a3[1,:2,1]

array([10, 13])

# Iterating

In [102]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [108]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [110]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [111]:
for i in np.nditer(a3):
    print(i)
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [113]:
#transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [114]:
#ravel 
#ravel convert any dimension array in 1D
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [116]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [117]:
#horizontal stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [118]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [119]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [122]:
#vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [123]:
#horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [131]:
#vertical splitting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]